### ISSUE TITLE
V-Tweaks crash on item pickup

### ISSUE THREAD

**Issue by XikoCat** [oitsjustjose/V-Tweaks#110]
Whenever I pickup an Item the server crashes.

VTweaks-1.20.1-4.0.12
Forge 47.2.6
Minecraft 1.20.1

```
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at TRANSFORMER/vtweaks@4.0.12/com.oitsjustjose.vtweaks.common.tweaks.entity.TraderStonks.process(TraderStonks.java:141)
	at TRANSFORMER/vtweaks@4.0.12/com.oitsjustjose.vtweaks.common.tweaks.entity.__TraderStonks_process_ServerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.6/net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:945)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	... 10 more

[25Nov2023 10:57:19.772] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/Lists
	at com.oitsjustjose.vtweaks.common.tweaks.entity.TraderStonks.process(TraderStonks.java:141) ~[VTweaks-1.20.1-4.0.12.jar%23497!/:4.0.12]
	at com.oitsjustjose.vtweaks.common.tweaks.entity.__TraderStonks_process_ServerTickEvent.invoke(.dynamic) ~[VTweaks-1.20.1-4.0.12.jar%23497!/:4.0.12]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:945) ~[forge-1.20.1-47.2.6-universal.jar%23520!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:812) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.compress.utils.Lists
	... 10 more
```

**Comment by oitsjustjose** [comment]
Resolved via b00bc1cf94e4ca02a7ded16586092de0a90f6d2b - sorry about that!
