### ISSUE TITLE
TraderStonks crashes on 4.0.13 1.19.2

### ISSUE THREAD

**Issue by sndmax** [oitsjustjose/V-Tweaks#115]
After updating from 4.0.8 to 4.0.13 server started daily crashing with same error. 
Using this pack https://www.curseforge.com/minecraft/modpacks/life-in-the-village-3/files/5054001 1.19.2

`java.lang.UnsupportedOperationException: null
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142) ~[?:?] {}
	at java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147) ~[?:?] {}
	at com.oitsjustjose.vtweaks.common.tweaks.entity.TraderStonks.process(TraderStonks.java:98) ~[VTweaks-1.19.2-4.0.13.jar%23636!/:4.0.13] {re:classloading}
	at com.oitsjustjose.vtweaks.common.tweaks.entity.__TraderStonks_process_LivingDropsEvent.invoke(.dynamic) ~[VTweaks-1.19.2-4.0.13.jar%23636!/:4.0.13] {re:classloading,pl:eventbus:B}
`
[crash-2024-02-01_23.49.24-server.txt](https://github.com/oitsjustjose/V-Tweaks/files/14131059/crash-2024-02-01_23.49.24-server.txt)

**Comment by sndmax** [comment]
Only changing **wanderingTraderRecoveryEnabled** and **enableFlavorText** to **false** fixed the issue

**Comment by oitsjustjose** [comment]
Yeah this may take me a bit to fix - been quite busy as of late, just know that this is on my radar to fix soon. I should have set the "Villager Stonks" feature as disabled by default, it's less ready than I thought it was 😢

**Comment by sndmax** [comment]
Thank you dude
From my investigating it might be because of conflict with Corail Tombstone, server was crashing when player died and after that his grave did not appear

**Comment by leafreynolds** [comment]
Additional crash log related to traderstonks crashes, in case it is helpful :)

[crash-2024-03-25_21.40.18-server.txt](https://github.com/oitsjustjose/V-Tweaks/files/14750331/crash-2024-03-25_21.40.18-server.txt)

**Comment by JuliadSmithe** [comment]
Hello, is there any temp fixes to this issue?  do I change wanderingTraderRecoveryEnabled and enableFlavorText to false?

[crash-2025-03-05_15.43.54-server.txt](https://github.com/user-attachments/files/19084704/crash-2025-03-05_15.43.54-server.txt)

**Comment by oitsjustjose** [comment]
1.19.2 is no longer supported, I think your only choice would be to disable the feature entirely.
